# Generated by Django 3.1.2 on 2020-10-15 15:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('businessname', models.CharField(blank=True, max_length=255, null=True)),
                ('taxnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street_details', models.CharField(blank=True, max_length=500, null=True)),
                ('business_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('restaurant_contact_person', models.FileField(blank=True, null=True, upload_to='')),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('restaurant_cover_photo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
